// File generated by FlutterFire CLI.
// Do not edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXkQ3mP9d7rLwK2eU5vTnC8oYjMpA1fGh',
    appId: '1:481230945678:android:a7e3f2b8c1d9e4f5a6b7',
    messagingSenderId: '481230945678',
    projectId: 'food-run-prod',
    storageBucket: 'food-run-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQ7nV3wX8yZ1kR4sT6pU9vWj2eF5gHi',
    appId: '1:481230945678:ios:b8f4a3c7d2e1f6a7b8c9',
    messagingSenderId: '481230945678',
    projectId: 'food-run-prod',
    storageBucket: 'food-run-prod.appspot.com',
    iosBundleId: 'ru.foodrun.client',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnP8qW4xY5zA2bS7tV9uXk3dG6hJ1mLo',
    appId: '1:481230945678:web:c9a5b4d8e3f2a7b6c5d4',
    messagingSenderId: '481230945678',
    projectId: 'food-run-prod',
    storageBucket: 'food-run-prod.appspot.com',
    authDomain: 'food-run-prod.firebaseapp.com',
  );
}
